### PR TITLE
Hip resource device guards.

### PR DESCRIPTION
**Pull request by mdavis36**
This PR adds device and memory size guards to mirror the functionality of Cuda resource. The size guards on memory operations are needed to get some failing tests to work in RAJA.

### CODE REVIEW

**Comment by mdavis36** [comment]
@trws This is green now, are you good with this? we need it for https://github.com/LLNL/RAJA/pull/1054

**Comment by trws** [comment]
Are the formatting changes from clang-format using the project config or something else? Otherwise I think this is fine, would prefer to have a test that at least calls it though.

**Comment by mdavis36** [comment]
I just copied the formatting from the cuda resource file.

**Comment by trws** [comment]
Fair enough.

**Pull request merged**
