### PR TITLE
Add rvalue get for tuples

### LINKED ISSUE #116: camp::get(camp::tuple) does not support rvalue references
It looks like camp only supports the lvalue variants of get with tuple. https://en.cppreference.com/w/cpp/utility/tuple/get
We would like to use a forwarding tuple to manipulate and forward the args to the ForallParamPack in the new reducer API PR. https://github.com/LLNL/RAJA/pull/1004

### PR DESCRIPTION
**Pull request by MrBurmark**
Here is my attempt to add support for rvalue forms of get with tuple.
This fixes #116.

### CODE REVIEW

**Review by trws — CHANGES_REQUESTED** [review]
I quite like this, but we need some tests here to ensure that the rvalue getters work as necessary. Probably not a ton to do there, but at least some basic "make_tuple(0).get()" or similar for a few different situations so we have a smoke test for this would make me a lot more comfortable it wont accidentally be broken down the line.

**Comment by MrBurmark** [comment]
Of course, I'll add tests.

**Comment by rhornung67** [comment]
I think we should get these changes in for the release.

**Comment by trws** [comment]
Does it break any external APIs in raja?  It's an ABI break because of the new overloads but if the API level at least at raja is ok I'm a lot less worried about the fallout.

**Comment by trws** [comment]
That seems pretty reasonable.

**Comment by trws** [comment]
@MrBurmark, do you consider this good to go? Tests look pretty good, I would normally include some actual executable tests in with the static asserts but you have really good coverage there so we might be alright in this case.

**Comment by MrBurmark** [comment]
I'll add some executable tests if its what you would do.

**Review by trws — APPROVED** [review]

**Comment by trws** [comment]
Looks great!

**Pull request merged**
