### PR TITLE
EventProxy stores resource by value.

### PR DESCRIPTION
**Pull request by mdavis36**
Event Proxy stores the internal resource by value. 

This is in relation to https://github.com/LLNL/RAJA/pull/1054

### CODE REVIEW

**Comment by trws** [comment]
I like this direction.  Assuming it's tweaked to get the tests green LGTM.

**Comment by MrBurmark** [comment]
Should resource get_default now return by value as well?

**Comment by trws** [comment]
For encapsulation reasons I suppose that might make sense.  It wouldn't really change anything for dangling references unless someone uses `decltype(auto)` or similar, but it wouldn't hurt either and would make it impossible for callers to modify the default value through it which seems like a good thing.

**Comment by mdavis36** [comment]
@trws @MrBurmark is this good to go?

**Review by trws — APPROVED** [review]
I'm happy. :shipit:

**Pull request merged**
