### PR TITLE
Add missing header to cuda resource

### PR DESCRIPTION
**Pull request by adayton1**
* Several resources were missing the <mutex> include
* Some other headers do not need to be included if certain configurations are not enabled

### CODE REVIEW

**Review by trws — DISMISSED** [review]
Good stuff, thanks @adayton1!

**Comment by trws** [comment]
Bah, looks like the ubuntu bionic-based containers are no longer supported, I'll pop up a commit here so we can get the build tests run.

**Review by MrBurmark — APPROVED** [review]
We should probably do the same for the other resources.

**Comment by adayton1** [comment]
> We should probably do the same for the other resources.

Good call. Done.

**Review by MrBurmark — APPROVED** [review]

**Comment by trws** [comment]
@adayton1, would you mind doing a merge or rebase here with the updated test containers so we can get the CI cuda builds going on this? I'm happy with it but would prefer to see those green before a merge.

**Comment by trws** [comment]
This branch is configured not to allow maintainers to merge or rebase, would be happy to move this forward if we can get the tests going.

**Comment by adayton1** [comment]
Sorry, I’ve been on vacation. I just merged in main, so hopefully that will take care of it. I’ll be back on vacation this afternoon until next week.

**Comment by trws** [comment]
All passed, thanks @adayton1!

**Pull request merged**
