### PR TITLE
Revert detect current gpu until config issues can be fixed

### PR DESCRIPTION
**Pull request by MrBurmark**
See https://github.com/LLNL/camp/pull/131#issuecomment-1554819856

### CODE REVIEW

**Comment by rhornung67** [comment]
@MrBurmark a brief PR description would be good so @trws knows what this is about.

**Comment by trws** [comment]
Especially with the build breakage, I assume something happened downstream? Do we have a project building off of main here rather than releases?

**Comment by rhornung67** [comment]
@trws yes, we build against camp main for RAJA PRs to merge into RAJA main or dev.  The issue we have is that BLT has no support for adding the CUDA driver library to the link line, which is needed with Jason's last PR that was merged.  Chris plans to rework the CUDA support in BLT to include what we need among other things, but we our GitLab CI testing on lassen is a smoking pile at the moment. I've spent some time playing with this, but I don't know enough about CMake to unravel what BLT is doing and how to do the right thing as far as CMake is concerned.

**Comment by trws** [comment]
Got it, that makes sense. If we can get the build fixed here, I'll take it ASAP.  I'm on personal travel at the moment and not in a position to dig in, but can certainly hit merge when I hear it's safe.

**Review by rhornung67 — APPROVED** [review]

**Comment by rhornung67** [comment]
@MrBurmark can we merge this, or do we need approval from @trws? Hopefully, this restores our GitLab CI for now.

**Comment by trws** [comment]
Merged. If you don't have rights to merge here when necessary, let me know and I'll add it when we're done with the funeral festivities today.

**Pull request merged**
