### PR TITLE
Export BLT TPL targets

### PR DESCRIPTION
**Pull request by davidbeckingsale**

### CODE REVIEW

**Comment by davidbeckingsale** [comment]
@trws can you take a look at this when you get a chance? Let me know if you have any questions.

**Comment by trws** [comment]
Looks like it's purely additive, does this take care of our exported targets issue, or at least part of it?

**Comment by davidbeckingsale** [comment]
Yup, I have been testing this branch in the Umpire PR. With these changes, a camp built as part of Umpire will work in a non-BLT CMake project.

**Comment by trws** [comment]
That's absolutely fantastic.  Approved!  Want an RC release or similar for this?

**Review by trws — APPROVED** [review]

**Comment by davidbeckingsale** [comment]
I can work off main for now - thanks!

**Pull request merged**
