### PR TITLE
Move private hip/cuda constructor to public

### PR DESCRIPTION
**Pull request by artv3**
Resolves issue #44

### CODE REVIEW

**Comment by trws** [comment]
I'm good with this change, vaguely nervous we might end up with that being ambiguous in some case down the line but if it's passing now it should be alright.  Maybe put in a test for it just to make sure this doesn't slip past us?

**Comment by artv3** [comment]
> I'm good with this change, vaguely nervous we might end up with that being ambiguous in some case down the line but if it's passing now it should be alright. Maybe put in a test for it just to make sure this doesn't slip past us?

Sure! Sounds good. Regarding the test, do you just mean exercise calling the constructor with a specified stream? Just want to double check what the test should look like.

**Comment by trws** [comment]
Yup, pretty much just construct one, maybe do something with it and wait on it.  The main worry is that we end up with the call to the constructors being ambiguous on some platform, so anything that actually calls it should show us that.

**Comment by artv3** [comment]
@trws , I pushed up a couple of test, but I couldn't figure out how to make one resource wait for another. Additionally, when trying to test on an AMD platform, I tried configuring the code via `cmake -DENABLE_HIP=ON ..' from a build directory and it wasn't picking up the hip compiler -- so the hip tests are untested right now.  If you suggestions I can make the adjustments for the tests.

**Comment by trws** [comment]
Ok, the tests work.  Two last things:

1. rebase or merge so we don't have conflicts
2. remove the `dev` argument from the stream constructor, it should never have been there since the stream encodes the device already and it's just a foot-gun.

**Comment by artv3** [comment]
> Ok, the tests work. Two last things:
> 
>     1. rebase or merge so we don't have conflicts
> 
>     2. remove the `dev` argument from the stream constructor, it should never have been there since the stream encodes the device already and it's just a foot-gun.

Regarding 2. If we remove the device specification that triggers the guard error: 

```
C++ exception with description "campCudaErrchk(cudaSetDevice(device)) invalid device ordinal /camp/include/camp/resource/cuda.hpp:34" thrown in the test body.
```

Reading around, I think we can get the device ID based on a given context. Perhaps something with the sequence of calls?
 
```
CUresult cuStreamGetCtx ( CUstream hStream, CUcontext* pctx );
CUresult cuCtxSetCurrent ( CUcontext ctx ) 
CUresult cuCtxGetDevice ( CUdevice* device ) 
```

Is that what you had in mind?

**Comment by trws** [comment]
Yeah basically, be sure to pop the stream’s context back off though so we don’t mess up the calling code.

On May 23, 2021, at 3:49 PM, Arturo Vargas ***@***.***> wrote:

﻿

Ok, the tests work. Two last things:

1. rebase or merge so we don't have conflicts

2. remove the `dev` argument from the stream constructor, it should never have been there since the stream encodes the device already and it's just a foot-gun.


Regarding 2. If we remove the device specification that triggers the guard error:

C++ exception with description "campCudaErrchk(cudaSetDevice(device)) invalid device ordinal /camp/include/camp/resource/cuda.hpp:34" thrown in the test body.


Reading around, I think we can get the device ID based on a given context. Perhaps something with the sequence of calls?

CUresult cuStreamGetCtx ( CUstream hStream, CUcontext* pctx );
CUresult cuCtxSetCurrent ( CUcontext ctx )
CUresult cuCtxGetDevice ( CUdevice* device )


Is that what you had in mind?

**Comment by artv3** [comment]
@trws, one quick question. It looks like I need to add the `cuda.h` header; however I'm not sure how to add the `-lcudart` flag to the build system. Otherwise we get the following error: 
```
undefined reference to `cuStreamGetCtx'
```

**Comment by artv3** [comment]
@trws I seem to be having some trouble with CMAKE here. I tried adding cudart to the `target_link_libraries` under `test/CMakeLists.txt` like this: `target_link_libraries(${TESTNAME} camp_cuda cudart)`.  But still hit the same error... any chance you might be able to push up a fix? --- I'm feeling a bit stuck here

**Comment by trws** [comment]
Have a look at this version.  I rebased it and reworked it a bit.  My main reason for wanting the argument gone was that in some cases it's possible the constructor signatures would be ambiguous, which would be pretty bad, so I left it private in case we need to do something about that and made a new static method `CudaFromStream` to create the thing. This avoids the context issue and takes care of the merge conflicts.  Work for you @artv3?

**Comment by artv3** [comment]
Looks great to me! Thanks!

**Pull request merged**
