### PR TITLE
fix build and install of windows DLLs

### PR DESCRIPTION
**Pull request by trws**

### CODE REVIEW

**Review by davidbeckingsale — APPROVED** [review]

**Review by rhornung67 — APPROVED** [review]
Thanks @trws I hope this works with RAJA.

**Comment by trws** [comment]
Ok, this should be good to go.  It's failing on an asan issue @davidbeckingsale found, I have the containers rebuilding upstream to fix that, but it could take a day to propagate.  @rhornung67, @davidbeckingsale, I tested this with raja on my windows system without issues, would you like to give it a whirl before I merge and tag this?

**Comment by rhornung67** [comment]
@trws trying it in this PR: https://github.com/LLNL/RAJA/pull/1227

**Comment by rhornung67** [comment]
@trws RAJA windows shared passed on azure. the others are still running. so this looks good to go. 👍

**Pull request merged**
